function results = DTU10MW_blade_response(cfg)
% Run this function without arguments from 01_Code in MATLAB R2023b.
% Inputs and outputs are located relative to this file; no extra toolbox is required.
% The wind-speed figures show steady mean displacements, rotor-plane radius,
% and total elastic tip twist. Section stiffness uses the direct elastic twist.

root_dir = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(root_dir,'src')));
if nargin < 1 || isempty(cfg)
    cfg = default_DTU10MW_config();
end
data = load_DTU10MW_data(cfg);
data.twist_coupling_factor = cfg.twist_coupling_factor;
if ~isfolder(cfg.paths.results_dir), mkdir(cfg.paths.results_dir); end
if ~isfolder(cfg.paths.figure_dir), mkdir(cfg.paths.figure_dir); end

model_static = assemble_blade_matrices(cfg,data,0,0,[]);
modes_static = solve_blade_modes(model_static,cfg.structure.mode_count);
Omega_rated = double(data.manifest.maximum_rpm)*2*pi/60;
model_rated = assemble_blade_matrices(cfg,data,Omega_rated,0,[]);
modes_rated = solve_blade_modes(model_rated,cfg.structure.mode_count);
mode = (1:numel(modes_static.frequency_hz)).';
modal_summary = table(mode,modes_static.frequency_hz,modes_rated.frequency_hz, ...
    modes_static.classification,modes_static.flap_fraction, ...
    'VariableNames',{'mode','static_frequency_Hz','rated_frequency_Hz', ...
    'classification','static_flap_fraction'});

if isempty(cfg.analysis.wind_speeds_m_s)
    wind_speeds = unique([double(data.operating.wind_speed_m_s(:));data.V_rated]);
else
    wind_speeds = unique(cfg.analysis.wind_speeds_m_s(:));
end
n_wind = numel(wind_speeds);
summary_rows = repmat(empty_summary_row(),n_wind,1);
cases = repmat(struct('wind_speed_m_s',0,'steady_history_file','', ...
    'rated_spanwise_file','','rated_stiffness_file',''),n_wind,1);
rated_stiffness_table = table();
twist_coupling_rated_file = '';

fprintf('Running %d DTU 10 MW operating points with %d azimuth samples...\n', ...
    n_wind,cfg.time.azimuth_samples);
for k = 1:n_wind
    V = wind_speeds(k);
    rpm = interp1(data.operating.wind_speed_m_s,data.operating.rpm,V,'pchip');
    pitch_deg = interp1(data.operating.wind_speed_m_s, ...
        data.operating.pitch_deg,V,'pchip');
    Omega = rpm*2*pi/60;
    periodic = prepare_periodic_state(cfg,data,V,Omega,deg2rad(pitch_deg));
    response = simulate_periodic_response(cfg,periodic);
    equivalent_radius = compute_equivalent_radius(data,periodic,response);
    twist_components = postprocess_twist_components(cfg,data,V,Omega, ...
        deg2rad(pitch_deg),periodic);
    summary_rows(k) = make_summary_row(V,rpm,pitch_deg,periodic,response, ...
        equivalent_radius,twist_components);

    steady = response.steady_index;
    history_table = table(response.history.time_s(steady).', ...
        response.tip_flap_m(steady).',response.tip_edge_m(steady).', ...
        equivalent_radius.dynamic_m(steady).', ...
        'VariableNames',{'time_s','tip_flap_m','tip_edge_m', ...
        'equivalent_radius_m'});
    history_file = fullfile(cfg.paths.results_dir, ...
        sprintf('steady_tip_history_V%04.1f.mat',V));
    save(history_file,'history_table','-v7.3');
    cases(k).wind_speed_m_s = V;
    cases(k).steady_history_file = fullfile('03_Results','MATLAB_Data', ...
        sprintf('steady_tip_history_V%04.1f.mat',V));

    if abs(V-data.V_rated) < 1e-9
        ref = periodic.reference_state;
        full = ref.q_static_full;
        spanwise = table(ref.model.mesh.r,full(1:4:end),full(3:4:end), ...
            interp1(ref.twist.r_structure,ref.twist.psi_structure_rad, ...
            ref.model.mesh.r,'pchip'), ...
            'VariableNames',{'r_m','flap_static_m','edge_static_m', ...
            'elastic_twist_rad'});
        spanwise_file = fullfile(cfg.paths.results_dir, ...
            'rated_spanwise_response.mat');
        save(spanwise_file,'spanwise','-v7.3');
        cases(k).rated_spanwise_file = fullfile('03_Results','MATLAB_Data', ...
            'rated_spanwise_response.mat');

        elastic_twist_mean = mean(periodic.twist_structure_samples_rad,2);
        stiffness = transform_section_stiffness(data,data.structure.r_m, ...
            deg2rad(pitch_deg),elastic_twist_mean);
        stiffness_table = make_stiffness_table(data,stiffness);
        rated_stiffness_table = stiffness_table;
        stiffness_file = fullfile(cfg.paths.results_dir, ...
            'stiffness_rated.mat');
        save(stiffness_file,'stiffness_table','-v7.3');
        cases(k).rated_stiffness_file = fullfile('03_Results','MATLAB_Data', ...
            'stiffness_rated.mat');

        twist_coupling_table = make_twist_coupling_table( ...
            data,periodic.reference_state.twist);
        twist_coupling_rated_file = fullfile(cfg.paths.results_dir, ...
            'twist_coupling_rated.mat');
        save(twist_coupling_rated_file,'twist_coupling_table','-v7.3');
        twist_coupling_rated_file = fullfile('03_Results','MATLAB_Data', ...
            'twist_coupling_rated.mat');
    end
    fprintf(['  V=%5.1f m/s: flap mean/max=%7.3f/%7.3f m, ' ...
        'edge mean/max=%7.3f/%7.3f m, direct elastic twist=%6.3f deg, rev=%d.\n'], ...
        V,response.metrics_flap.mean,response.metrics_flap.maximum, ...
        response.metrics_edge.mean,response.metrics_edge.maximum, ...
        mean(periodic.tip_twist_samples_rad)*180/pi, ...
        response.revolutions_completed);
end

summary = struct2table(summary_rows);
save(fullfile(cfg.paths.results_dir,'wind_speed_summary.mat'),'summary','-v7.3');
save(fullfile(cfg.paths.results_dir,'modal_summary.mat'),'modal_summary','-v7.3');
figure_files = strings(0,1);
if cfg.output.save_figures
    figure_files = save_response_figures(cfg,summary,modal_summary, ...
        rated_stiffness_table);
end

results.cfg = cfg;
results.cfg.paths.root_dir = '.';
results.cfg.paths.data_dir = '02_Input_Parameters';
results.cfg.paths.results_dir = fullfile('03_Results','MATLAB_Data');
results.cfg.paths.figure_dir = fullfile('03_Results','Figures');
results.manifest = data.manifest;
results.data_validation = data.validation;
results.modal_summary = modal_summary;
results.wind_speed_summary = summary;
results.case_files = cases;
results.figure_files = erase(figure_files, string(cfg.paths.root_dir)+filesep);
results.twist_coupling_rated_file = twist_coupling_rated_file;
save(fullfile(cfg.paths.results_dir,'DTU10MW_results.mat'),'results','-v7.3');
end

function row = empty_summary_row()
names = {'wind_speed_m_s','rpm','pitch_deg','flap_mean_m','flap_max_m', ...
    'flap_min_m','flap_amplitude_m','edge_mean_m','edge_max_m','edge_min_m', ...
    'edge_amplitude_m','tip_elastic_twist_mean_deg', ...
    'tip_elastic_twist_max_deg','tip_elastic_twist_min_deg', ...
    'tip_elastic_twist_cm_mean_deg', ...
    'tip_elastic_twist_force_arm_mean_deg','tip_geometric_twist_deg', ...
    'tip_baseline_principal_axis_deg','tip_section_twist_mean_deg', ...
    'tip_section_twist_max_deg','tip_section_twist_min_deg', ...
    'tip_stiffness_axis_angle_mean_deg', ...
    'tip_geometry_plus_elastic_mean_deg', ...
    'tip_total_section_angle_mean_deg', ...
    'effective_radius_mean_m','effective_radius_max_m', ...
    'effective_radius_min_m','blade_thrust_kN','rotor_thrust_kN', ...
    'blade_torque_MNm','rotor_power_MW','periodic_revolutions', ...
    'periodic_relative_error','periodic_converged','max_coupling_iterations', ...
    'tip_twist_direct_mean_deg','tip_twist_coupling_mean_deg', ...
    'tip_twist_total_mean_deg','tip_twist_total_max_deg', ...
    'tip_twist_total_min_deg','tip_twist_direct_deg', ...
    'tip_twist_coupling_raw_deg', ...
    'tip_twist_coupling_corrected_deg','tip_twist_total_deg'};
row = cell2struct(num2cell(zeros(size(names))),names,2);
end

function row = make_summary_row(V,rpm,pitch_deg,periodic,response,radius,twist_components)
row = empty_summary_row();
row.wind_speed_m_s = V;
row.rpm = rpm;
row.pitch_deg = pitch_deg;
row.flap_mean_m = response.metrics_flap.mean;
row.flap_max_m = response.metrics_flap.maximum;
row.flap_min_m = response.metrics_flap.minimum;
row.flap_amplitude_m = response.metrics_flap.amplitude;
row.edge_mean_m = response.metrics_edge.mean;
row.edge_max_m = response.metrics_edge.maximum;
row.edge_min_m = response.metrics_edge.minimum;
row.edge_amplitude_m = response.metrics_edge.amplitude;
tip_twist_deg = rad2deg(periodic.tip_twist_samples_rad);
row.tip_elastic_twist_mean_deg = mean(tip_twist_deg);
row.tip_elastic_twist_max_deg = max(tip_twist_deg);
row.tip_elastic_twist_min_deg = min(tip_twist_deg);
row.tip_elastic_twist_cm_mean_deg = mean(rad2deg( ...
    periodic.tip_twist_cm_samples_rad));
row.tip_elastic_twist_force_arm_mean_deg = mean(rad2deg( ...
    periodic.tip_twist_force_arm_samples_rad));
row.tip_geometric_twist_deg = periodic.geometric_tip_twist_deg;
row.tip_baseline_principal_axis_deg = ...
    periodic.baseline_principal_axis_tip_deg;
tip_section_twist_deg = row.tip_baseline_principal_axis_deg+tip_twist_deg;
row.tip_section_twist_mean_deg = mean(tip_section_twist_deg);
row.tip_section_twist_max_deg = max(tip_section_twist_deg);
row.tip_section_twist_min_deg = min(tip_section_twist_deg);
row.tip_stiffness_axis_angle_mean_deg = ...
    row.tip_section_twist_mean_deg+pitch_deg;
row.tip_geometry_plus_elastic_mean_deg = periodic.geometric_tip_twist_deg+ ...
    row.tip_elastic_twist_mean_deg;
row.tip_total_section_angle_mean_deg = ...
    row.tip_geometry_plus_elastic_mean_deg+pitch_deg;
row.effective_radius_mean_m = radius.mean_m;
row.effective_radius_max_m = radius.maximum_m;
row.effective_radius_min_m = radius.minimum_m;
row.blade_thrust_kN = mean(periodic.blade_thrust_samples_N)/1e3;
row.rotor_thrust_kN = 3*row.blade_thrust_kN;
row.blade_torque_MNm = mean(periodic.blade_torque_samples_Nm)/1e6;
row.rotor_power_MW = 3*periodic.Omega_rad_s* ...
    mean(periodic.blade_torque_samples_Nm)/1e6;
row.periodic_revolutions = response.revolutions_completed;
row.periodic_relative_error = response.periodic_relative_error;
row.periodic_converged = response.periodic_converged;
row.max_coupling_iterations = max(periodic.coupling_iterations);
row.tip_twist_direct_mean_deg = row.tip_elastic_twist_mean_deg;
row.tip_twist_coupling_mean_deg = mean(rad2deg( ...
    twist_components.coupling_samples_rad));
row.tip_twist_total_mean_deg = mean(rad2deg( ...
    twist_components.total_samples_rad));
row.tip_twist_total_max_deg = max(rad2deg( ...
    twist_components.total_samples_rad));
row.tip_twist_total_min_deg = min(rad2deg( ...
    twist_components.total_samples_rad));
row.tip_twist_direct_deg = mean(rad2deg( ...
    twist_components.direct_samples_rad));
row.tip_twist_coupling_raw_deg = mean(rad2deg( ...
    twist_components.coupling_raw_samples_rad));
row.tip_twist_coupling_corrected_deg = mean(rad2deg( ...
    twist_components.coupling_corrected_samples_rad));
row.tip_twist_total_deg = mean(rad2deg( ...
    twist_components.total_samples_rad));
end

function output = make_stiffness_table(data,stiffness)
r = stiffness.r_m;
output = table(r,r-double(data.manifest.R_hub_m), ...
    stiffness.EI_principal_x_Nm2,stiffness.EI_principal_y_Nm2, ...
    stiffness.EI_principal_x_Nm2,stiffness.EI_principal_y_Nm2, ...
    stiffness.EI_flap_effective_Nm2,stiffness.EI_edge_effective_Nm2, ...
    stiffness.EI_flap_edge_coupling_Nm2, ...
    stiffness.EI_flap_edge_coupling_Nm2,stiffness.GJ_Nm2, ...
    rad2deg(stiffness.geometric_twist_rad), ...
    rad2deg(stiffness.structural_pitch_rad), ...
    rad2deg(stiffness.baseline_principal_axis_rad), ...
    rad2deg(stiffness.pitch_rad),rad2deg(stiffness.elastic_twist_rad), ...
    rad2deg(stiffness.gamma_increment_rad), ...
    rad2deg(stiffness.gamma_increment_rad), ...
    rad2deg(stiffness.total_axis_angle_rad), ...
    'VariableNames',{'r_m','r_from_blade_root_m', ...
    'EI_principal_x_Nm2','EI_principal_y_Nm2', ...
    'EI_zeta_Nm2','EI_eta_Nm2', ...
    'EI_flap_effective_Nm2','EI_edge_effective_Nm2', ...
    'EI_flap_edge_coupling_Nm2','EI_coupling_Nm2','GJ_Nm2', ...
    'geometric_twist_deg', ...
    'structural_pitch_deg','baseline_principal_axis_deg','pitch_deg', ...
    'elastic_twist_deg','gamma_increment_deg','gamma_deg', ...
    'total_axis_angle_deg'});
end

function components = postprocess_twist_components( ...
        cfg,data,V,Omega,pitch_rad,periodic)
n_azimuth = numel(periodic.azimuth_rad);
direct = periodic.tip_twist_samples_rad(:);
coupling_raw = zeros(n_azimuth,1);
coupling_corrected = zeros(n_azimuth,1);
coupling_raw(1) = ...
    periodic.reference_state.twist.tip_twist_coupling_raw_rad;
coupling_corrected(1) = ...
    periodic.reference_state.twist.tip_twist_coupling_corrected_rad;
r_structure = double(data.structure.r_m(:));
r_aero = double(data.aerodynamic_stations.r_m(:));
for j = 2:n_azimuth
    psi_aero = interp1(r_structure, ...
        periodic.twist_structure_samples_rad(:,j),r_aero,'pchip');
    bem = bem_solver_DTU10MW(cfg,data,V,Omega,pitch_rad, ...
        periodic.azimuth_rad(j),psi_aero);
    twist = compute_elastic_twist(data,bem);
    coupling_raw(j) = twist.tip_twist_coupling_raw_rad;
    coupling_corrected(j) = twist.tip_twist_coupling_corrected_rad;
end
components.direct_samples_rad = direct;
components.coupling_samples_rad = coupling_raw;
components.coupling_raw_samples_rad = coupling_raw;
components.coupling_corrected_samples_rad = coupling_corrected;
components.total_samples_rad = direct+coupling_corrected;
end

function output = make_twist_coupling_table(data,twist)
r = twist.r_structure;
output = table(r,r-double(data.R_hub), ...
    twist.normal_load_structure_Npm,twist.tangential_load_structure_Npm, ...
    twist.internal_shear_flap_N,twist.internal_shear_edge_N, ...
    twist.shear_center_x_m,twist.shear_center_y_m, ...
    twist.internal_torque_direct_Nm, ...
    twist.internal_torque_coupling_raw_Nm, ...
    twist.internal_torque_coupling_corrected_Nm, ...
    twist.internal_torque_total_Nm,twist.GJ_Nm2, ...
    twist.kappa_twist_direct_radpm, ...
    twist.kappa_twist_coupling_raw_radpm, ...
    twist.kappa_twist_coupling_corrected_radpm, ...
    twist.kappa_twist_total_radpm, ...
    rad2deg(twist.elastic_twist_direct_rad), ...
    rad2deg(twist.elastic_twist_coupling_raw_rad), ...
    rad2deg(twist.elastic_twist_coupling_corrected_rad), ...
    rad2deg(twist.elastic_twist_total_rad), ...
    'VariableNames',{'r_m','r_from_blade_root_m','normal_load_Npm', ...
    'tangential_load_Npm','internal_shear_flap_N','internal_shear_edge_N', ...
    'shear_center_x_m','shear_center_y_m','internal_torque_direct_Nm', ...
    'internal_torque_coupling_raw_Nm', ...
    'internal_torque_coupling_corrected_Nm', ...
    'internal_torque_total_Nm','GJ_Nm2','kappa_direct_radpm', ...
    'kappa_coupling_raw_radpm','kappa_coupling_corrected_radpm', ...
    'kappa_total_radpm','twist_direct_deg','twist_coupling_raw_deg', ...
    'twist_coupling_corrected_deg','twist_total_deg'});
end
